#!/bin/sh

#
# Try to find the streaming JAR
#

PLACES="/usr/lib/hadoop-mapreduce/hadoop-streaming.jar /usr/local/hadoop/share/hadoop/tools/lib/hadoop-streaming-2.9.2.jar"
STREAM=""

for place in $PLACES; do
    if [ -f $place ]
    then
	STREAM="$place"
    fi
done

if [ -z "$STREAM" ]
then
    echo "Unable to find your streaming JAR"
    exit 1
fi
   
hdfs dfs -rm -r -f stream-output-step1
hdfs dfs -rm -r -f stream-output-step2
hdfs dfs -rm -r -f stream-output-final

hadoop jar /usr/lib/hadoop-mapreduce/hadoop-streaming.jar \
	-mapper Mapper1.py \
	-reducer Reducer1.py \
	-file Mapper1.py -file Reducer1.py \
	-input input -output stream-output-step1

hadoop jar /usr/lib/hadoop-mapreduce/hadoop-streaming.jar \
	-mapper Mapper1.py \
	-reducer Reducer2.py \
	-file Mapper1.py -file Reducer2.py \
	-input input/apat63_99.txt -input stream-output-step1/part* -output stream-output-step2

hadoop jar /usr/lib/hadoop-mapreduce/hadoop-streaming.jar \
	-mapper CheckCitationCountMapper.py \
	-reducer CheckCitationCountReducer.py \
	-file CheckCitationCountMapper.py -file CheckCitationCountReducer.py \
	-input input/apat63_99.txt -input stream-output-step2/part* -output stream-output-final
	
